
import {INTERNAL_SERVER_PLATFORM_PROVIDERS} from './server';

export var __platform_server_private__:
    {INTERNAL_SERVER_PLATFORM_PROVIDERS: typeof INTERNAL_SERVER_PLATFORM_PROVIDERS} = {
      INTERNAL_SERVER_PLATFORM_PROVIDERS: INTERNAL_SERVER_PLATFORM_PROVIDERS
    };
